AllCops:
  NewCops: enable

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Style/Documentation:
  Enabled: no

Style/EmptyMethod:
  EnforcedStyle: expanded

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required
